from enum import StrEnum


class Role(StrEnum):
    SYS_ADMIN = "SYS_ADMIN"
    TENANT_ADMIN = "TENANT_ADMIN"
    USER = "USER"


class AuditAction(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    USER_CREATED = "USER_CREATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    TENANT_CREATED = "TENANT_CREATED"
